# Generated by Django 3.1.2 on 2020-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='PhoneNumber',
            field=models.BigIntegerField(default='0'),
        ),
    ]
