# Generated by Django 3.1.2 on 2020-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUsApp', '0003_auto_20201008_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='PhoneNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
